language: go

go:
  - "1.14.x"
  - "1.15.x"
  - tip

sudo: false

git:
  depth: 1

env:
  - GO111MODULE=on
install:
  - pip install --user codecov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test ./...
  - cd tokenizer; go test -benchmem -bench .; cd ..

after_success:
  - |
    if [[ $TRAVIS_GO_VERSION = 1.15.x ]]
    then
      /bin/sh ./go-coverall.sh
    else
      echo skip coverage test, $TRAVIS_GO_VERSION
    fi
